function PlotSurfaces(app,sSurfaces)
            delete(app.PanelViewer.Children);
            template = load('axes.mat');
            app.currentAxes = template.axes;
            alpha = 1;
            ProtocolInfo = bst_get('ProtocolInfo');
            for i=1:length(sSurfaces)
                surf = sSurfaces{i};
                switch surf
                    case 'Cortex'                        
                        filename = fullfile(ProtocolInfo.SUBJECTS, app.currentSub.Surface(app.currentSub.iCortex).FileName);
                        surface = load(filename);
                        patch( app.currentAxes,...
                            'Faces',            surface.Faces, ...
                            'Vertices',         surface.Vertices,...
                            'VertexNormals',    surface.VertNormals, ...
                            'VertexNormalsMode', 'auto',...
                            'FaceNormals',      [],...
                            'FaceNormalsMode',  'auto',...
                            'FaceVertexCData',  [], ...
                            'FaceColor',        [255/255 204/255 204/255], ...
                            'FaceAlpha',        alpha, ...
                            'AlphaDataMapping', 'none', ...
                            'EdgeColor',        'none', ...
                            'EdgeAlpha',        alpha, ...
                            'LineWidth',         0.5,...
                            'LineJoin',         'miter',...
                            'AmbientStrength',  0.5, ...
                            'DiffuseStrength',  0.5, ...
                            'SpecularStrength', 0.2, ...
                            'SpecularExponent', 1, ...
                            'SpecularColorReflectance', 0.5, ...
                            'FaceLighting',     'gouraud', ...
                            'EdgeLighting',     'gouraud', ...
                            'Tag',              'cortex');
                        alpha = alpha - 0.60;

                    case 'InnerSkull'
                        filename = fullfile(ProtocolInfo.SUBJECTS, app.currentSub.Surface(app.currentSub.iInnerSkull).FileName);
                        surface = load(filename);
                        patch( app.currentAxes,...
                            'Faces',            surface.Faces, ...
                            'Vertices',         surface.Vertices,...
                            'VertexNormals',    surface.VertNormals, ...
                            'VertexNormalsMode', 'auto',...
                            'FaceNormals',      [],...
                            'FaceNormalsMode',  'auto',...
                            'FaceVertexCData',  [],...
                            'FaceColor',        [0.7 0.7 0.7], ...
                            'FaceAlpha',        alpha, ...
                            'AlphaDataMapping', 'none', ...
                            'EdgeColor',        'none', ...
                            'EdgeAlpha',        alpha, ...
                            'LineWidth',         0.5,...
                            'LineJoin',         'miter',...
                            'AmbientStrength',  0.5, ...
                            'DiffuseStrength',  0.5, ...
                            'SpecularStrength', 0.2, ...
                            'SpecularExponent', 1, ...
                            'SpecularColorReflectance', 0.5, ...
                            'FaceLighting',     'gouraud', ...
                            'EdgeLighting',     'gouraud', ...
                            'Tag',              'innerskull');
                        alpha = alpha - 0.10;

                    case 'OuterSkull'
                        filename = fullfile(ProtocolInfo.SUBJECTS, app.currentSub.Surface(app.currentSub.iOuterSkull).FileName);
                        surface = load(filename);
                        patch( app.currentAxes,...
                            'Faces',            surface.Faces, ...
                            'Vertices',         surface.Vertices,...
                            'VertexNormals',    surface.VertNormals, ...
                            'VertexNormalsMode', 'auto',...
                            'FaceNormals',      [],...
                            'FaceNormalsMode',  'auto',...
                            'FaceVertexCData',  [], ...
                            'FaceColor',        [0.7 0.7 0.7], ...
                            'FaceAlpha',        alpha, ...
                            'AlphaDataMapping', 'none', ...
                            'EdgeColor',        'none', ...
                            'EdgeAlpha',        alpha, ...
                            'LineWidth',         0.5,...
                            'LineJoin',         'miter',...
                            'AmbientStrength',  0.5, ...
                            'DiffuseStrength',  0.5, ...
                            'SpecularStrength', 0.2, ...
                            'SpecularExponent', 1, ...
                            'SpecularColorReflectance', 0.5, ...
                            'FaceLighting',     'gouraud', ...
                            'EdgeLighting',     'gouraud', ...
                            'Tag',              'outerskull');
                        alpha = alpha - 0.10;

                    case 'Scalp'
                        filename = fullfile(ProtocolInfo.SUBJECTS, app.currentSub.Surface(app.currentSub.iScalp).FileName);
                        surface = load(filename);
                        patch( app.currentAxes,...
                            'Faces',            surface.Faces, ...
                            'Vertices',         surface.Vertices,...
                            'VertexNormals',    surface.VertNormals, ...
                            'VertexNormalsMode', 'auto',...
                            'FaceNormals',      [],...
                            'FaceNormalsMode',  'auto',...
                            'FaceVertexCData',  [], ...
                            'FaceColor',        [0.7 0.7 0.7], ...
                            'FaceAlpha',        alpha, ...
                            'AlphaDataMapping', 'none', ...
                            'EdgeColor',        'none', ...
                            'EdgeAlpha',        alpha, ...
                            'LineWidth',         0.5,...
                            'LineJoin',         'miter',...
                            'AmbientStrength',  0.5, ...
                            'DiffuseStrength',  0.5, ...
                            'SpecularStrength', 0.2, ...
                            'SpecularExponent', 1, ...
                            'SpecularColorReflectance', 0.5, ...
                            'FaceLighting',     'gouraud', ...
                            'EdgeLighting',     'gouraud', ...
                            'Tag',              'scalp');
                        alpha = alpha - 0.10;
                end
            end
            set(app.currentAxes,"Parent",app.PanelViewer);
            rotate3d(app.currentAxes,'on');
            view(app.currentAxes,0,0);
        end
