function fig = PlotSourceTopography(Cortex,J,colorMap,title)
            fig = figure;
            template                = load('axes.mat');
            currentAxes             = template.axes;           
                       
            sources_iv              = sqrt(abs(J));
            sources_iv              = sources_iv/max(sources_iv(:));            
            smoothValue             = 0.66;
            SurfSmoothIterations    = 10;
            Vertices                = tess_smooth(Cortex.Vertices, smoothValue, SurfSmoothIterations, Cortex.VertConn, 1);
            
            patch(currentAxes, ...
                'Faces',Cortex.Faces, ...
                'Vertices',Vertices, ...
                'FaceVertexCData',Cortex.SulciMap*0.06+log(1+sources_iv), ...
                'FaceColor','interp', ...
                'EdgeColor','none', ...
                'AlphaDataMapping', 'none', ...
                'EdgeColor',        'none', ...
                'EdgeAlpha',        1, ...
                'BackfaceLighting', 'lit', ...
                'AmbientStrength',  0.5, ...
                'DiffuseStrength',  0.5, ...
                'SpecularStrength', 0.2, ...
                'SpecularExponent', 1, ...
                'SpecularColorReflectance', 0.5, ...
                'FaceLighting',     'gouraud', ...
                'EdgeLighting',     'gouraud', ...
                'FaceAlpha',1);
            set(currentAxes,'xcolor','w','ycolor','w','zcolor','w');            
            view(currentAxes,0,0);            
            colormap(currentAxes,colorMap.cmap_a);            
            set(currentAxes,"Parent",fig);
            rotate3d(currentAxes,'on'); 
            sgtitle(title);
        end        

