function PlotCortex(app, Cortex)            
           
            delete(app.PanelViewer.Children);
            template        = load('axes.mat');
            app.currentAxes = template.axes;
            % Selecting Hemisphere
            [Cortex, ~]     = app.split_hemisphere(Cortex);
            FaceColor =   app.PanelControls.Children(4).Value;
            if(app.PanelControls.Children(2).Value)
                FaceColor =   [0.6 0.6 0.6];
            end
            patch( app.currentAxes,...
                'Faces',            Cortex.Faces, ...
                'Vertices',         Cortex.Vertices,...
                'VertexNormals',    Cortex.VertNormals, ...
                'VertexNormalsMode', 'auto',...
                'FaceNormals',      [],...
                'FaceNormalsMode',  'auto',...
                'FaceVertexCData',  [], ...
                'FaceColor',        FaceColor, ...
                'FaceAlpha',        1, ...
                'AlphaDataMapping', 'none', ...
                'EdgeColor',        'none', ...
                'EdgeAlpha',        1, ...
                'LineWidth',         0.5,...
                'LineJoin',         'miter',...
                'AmbientStrength',  0.5, ...
                'DiffuseStrength',  0.5, ...
                'SpecularStrength', 0.2, ...
                'SpecularExponent', 1, ...
                'SpecularColorReflectance', 0.5, ...
                'FaceLighting',     'gouraud', ...
                'EdgeLighting',     'gouraud', ...
                'Tag',              'AnatSurface');
            if(app.PanelControls.Children(2).Value)
                sAtlas = Cortex.Atlas(Cortex.iAtlas);
                sScouts = sAtlas.Scouts;
                Vertices = Cortex.Vertices;
                Faces = Cortex.Faces;
                % Process each scout
                for i = 1:length(sScouts)
                    scoutColor = sScouts(i).Color;
                    % Get visible scouts vertices
                    iScoutVert = sScouts(i).Vertices;
                    patchVert = Vertices(iScoutVert,:);
                    scoutFaces = [];
                    countFace = 1;
                    vertMask = false(length(Vertices),1);
                    vertMask(iScoutVert) = true;
                    iFacesTmp = find(vertMask(Faces(:,1)));
                    iFacesTmp = iFacesTmp(vertMask(Faces(iFacesTmp,2)));
                    iFacesTmp = iFacesTmp(vertMask(Faces(iFacesTmp,3)));
                    patchFaces = Faces(iFacesTmp,:);
                    [~, patchFaces] = ismember(patchFaces, iScoutVert);
                    EdgeColor = 'none';
                    patchAlpha = 0.2;
                    patch(app.currentAxes,...
                        'Faces',            patchFaces, ...
                        'Vertices',         patchVert, ...
                        'FaceVertexCData',  scoutColor, ...
                        'FaceColor',        scoutColor, ...
                        'EdgeColor',        EdgeColor,...
                        'FaceAlpha',        1 - patchAlpha, ...
                        'BackFaceLighting', 'lit', ...
                        'Tag',              'ScoutPatch', ...
                        'AmbientStrength',  0.5, ...
                        'DiffuseStrength',  0.5, ...
                        'SpecularStrength', 0.2, ...
                        'SpecularExponent', 1, ...
                        'SpecularColorReflectance', 0.5, ...
                        'FaceLighting',     'gouraud', ...
                        'EdgeLighting',     'gouraud');
                end
            else
                delete(findobj(app.currentAxes, 'type', 'Patch', 'tag', 'ScoutPatch'));
            end  

            set(app.currentAxes,"Parent",app.PanelViewer);
            rotate3d(app.currentAxes,'on');
            view(app.currentAxes,180,90);            
        end        

